name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Printing PWD
        run: |
          cd .. & pwd & ls -l
      - name: Copy index.html to Azure VM
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa index.html ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }}:/var/www/html
        env:
          AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}

      - name: SSH into Azure VM and Restart Apache
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} "sudo systemctl restart apache2"
        env:
          AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}

      - name: Cleanup SSH key
        run: rm -f ~/.ssh/id_rsa
